#!/bin/bash
set -euo pipefail
# This transform script removes common Kubernetes metadata fields that often cause noise in diffs.
yq 'del(.metadata.annotations."kubectl.kubernetes.io/last-applied-configuration", .metadata.creationTimestamp, .metadata.generation, .metadata.resourceVersion, .metadata.uid, .status)'