#!/bin/bash
yq 'del(
  .status,
  .metadata.managedFields,
  .metadata.annotations["kubectl.kubernetes.io/last-applied-configuration"],
  .metadata.creationTimestamp,
  .metadata.resourceVersion,
  .metadata.uid
)'
