* Problem statement

The goal of this project is to enhance =argocd diff= and =kubectl diff=
by allowing to process manifests with arbitrary yq expression,
before applying the user's =KUBECTL_EXTERNAL_DIFF= program.

** Advanced examples

#+begin_src bash
  # Assume the script is called kdiff
  # Should output a helpful message
  kdiff --help

  # Diff only the resource specs
  # Use kubectl diff as default command, and forward all arguments after --
  kdiff --scope=.spec -- -rR overlays/staging

  # Show the diff for services and pods
  kdiff --kind=svc,po -- argocd diff myapp

  # Use kdiff with a predefined set of arguments as KUBECTL_EXTERNAL_DIFF
  # kdiff should know wether it is invoked interactively, or as KUBECTL_EXTERNAL_DIFF
  export KUBECTL_EXTERNAL_DIFF="kdiff --yq '... style=\"\" | del(.metadata.labels)'"
  kubectl diff -f mypod.yaml

  # The user should be able to use any diff tool
  KUBECTL_EXTERNAL_DIFF=fancydiff
  kdiff --ignore=.metadata.labels,.spec.affinity -- -f mydeploy.yaml
#+end_src


** Ideas

- Control over what is diffed
  - Limit the diff to a given =.kind= of resources, for example =Pod=
  - Limit the scope of the diff, for example to the resource =.spec=
  - Remove noisy fields from the diff, such as =last-applied-configuration=

- Ability to still choose custom diff tool
  - use any of =dyff=, =difftastic=, =delta= etc...

- Ability to use presets stored in $XDG_CONFIG/kdiff


** Design

- It should be possible to call the script interactively,
  or assign it directly to =KUBECTL_EXTERNAL_DIFF=
- If called interactively,
  the users original =KUBECTL_EXTERNAL_DIFF= should be taken into consideration


* Brainstorming instructions

- Help me brainstorm around this initial idea

- Help me produce and actionable plan, captured in Markdown format
- Structure your thoughts in three sections:
  - MVP design
    - Very actionable outline to code a minimal working version of the tool
  - Next steps
    - The most important improvements after MVP
  - Wild ideas
    - What inspires you!


* Context

The =kdiff= utility aims to improve the =kubectl diff= and =argocd
app diff= user experience by allowing to specify how manifests should be
transformed and compared.

#+begin_src sh
  # Arguments after -- are passed to kubectl by default
  kdiff --transform 'yq .spec' --compare 'diff -u --color' -- -f mypod.yaml

  # A --yq shorthand is provided for convenience,
  # and KUBECTL_EXRTERNAL_DIFF is honored.
  # Thus, the following call is equivalent
  KUBECTL_EXTERNAL_DIFF='diff -u --color'
  kdiff --yq=.spec  -- -f mypod.yaml
#+end_src



This is achieved by hooking into =KUBECTL_EXTERNAL_DIFF=, and
saving =--transform= and =--compare= executables in a *preset*.

A preset is a directory in ={HOME}/.config/kdiff= that contains two executables:
- =transform=, that takes a yaml stream on stdin and outputs a YAML stream.
- =compare=, that takes two files or two directories as arguments and outputs the diff

For example, a preset called =neat-dyff= that uses [[https://github.com/itaysk/kubectl-neat][kubectl-neat]] to de-clutter manifests and
[[https://github.com/homeport/dyff][dyff]] to compare them could be created thus:
#+begin_src sh
  PRESET_DIR=~/.config/kdiff/neat-dyff
  mkdir -p "${PRESET_DIR}"

  cat <<EOF > "${PRESET_DIR}"/transform
  #!/bin/bash
  kubectl-neat -f -
  EOF

  cat <<'EOF' > "${PRESET_DIR}"/compare
  #!/bin/bash
  dyff between --omit-header --set-exit-code "$1" "$2"
  EOF

  chmod -R +x "${PRESET_DIR}"
#+end_src

The preset can be used interactively,
or set as a default for all =kubectl diff= and =argocd app diff= calls.
#+begin_src sh
  # Use as default for all kubectl diff calls
  KUBECTL_EXTERNAL_DIFF="kdiff --preset neat-dyff"
  kubectl diff -f mypod.yaml

  # Use just this one time
  kiff --preset neat-dyff -- -f mypod.yaml
#+end_src

** KUBECTL_EXTERNAL_DIFF calling conventions

The following examples show how the =KUBECTL_EXTERNAL_DIFF= is called by =kubectl= and =argocd=

=kubectl diff= calls =KUBECTL_EXTERNAL_DIFF= once,
with two directories containing all the files to compare.
#+begin_example
$ export KUBECTL_EXTERNAL_DIFF=kdiff-inspect
$ k diff -f v1_configmap_argocd-cm.yaml -f v1_configmap_argocd-cmd-params-cm.yaml
Argument list: /tmp/LIVE-3407625460 /tmp/MERGED-4175425960
Left: /tmp/LIVE-3407625460
v1.ConfigMap.argocd.argocd-cm
v1.ConfigMap.argocd.argocd-cmd-params-cm
Right: /tmp/MERGED-4175425960
v1.ConfigMap.argocd.argocd-cm
v1.ConfigMap.argocd.argocd-cmd-params-cm
#+end_example

=argocd diff= calls =KUBECTL_EXTERNAL_DIFF= once for each pair of files to compare.
#+begin_example
$ export KUBECTL_EXTERNAL_DIFF=kdiff-inspect
$ argocd app diff myapp
===== /ServiceAccount argocd/argocd-redis-ha-haproxy ======
Argument list: /tmp/argocd-diff3488706002/argocd-redis-ha-haproxy-live.yaml /tmp/argocd-diff3488706002/argocd-redis-ha-haproxy
Left: /tmp/argocd-diff3488706002/argocd-redis-ha-haproxy-live.yaml
/tmp/argocd-diff3488706002/argocd-redis-ha-haproxy-live.yaml
Right: /tmp/argocd-diff3488706002/argocd-redis-ha-haproxy
/tmp/argocd-diff3488706002/argocd-redis-ha-haproxy

===== /ServiceAccount argocd/argocd-repo-server ======
Argument list: /tmp/argocd-diff74211896/argocd-repo-server-live.yaml /tmp/argocd-diff74211896/argocd-repo-server
Left: /tmp/argocd-diff74211896/argocd-repo-server-live.yaml
/tmp/argocd-diff74211896/argocd-repo-server-live.yaml
Right: /tmp/argocd-diff74211896/argocd-repo-server
/tmp/argocd-diff74211896/argocd-repo-server
#+end_example
