* Problem statement

The goal of this project is to enhance =argocd diff= and =kubectl diff=
by allowing to process manifests with arbitrary yq expression,
before applying the user's =KUBECTL_EXTERNAL_DIFF= program.

** Advanced examples

#+begin_src bash
  # Assume the script is called kdiff
  # Should output a helpful message
  kdiff --help

  # Diff only the resource specs
  # Use kubectl diff as default command, and forward all arguments after --
  kdiff --scope=.spec -- -rR overlays/staging

  # Show the diff for services and pods
  kdiff --kind=svc,po -- argocd diff myapp

  # Use kdiff with a predefined set of arguments as KUBECTL_EXTERNAL_DIFF
  # kdiff should know wether it is invoked interactively, or as KUBECTL_EXTERNAL_DIFF
  export KUBECTL_EXTERNAL_DIFF="kdiff --yq '... style=\"\" | del(.metadata.labels)'"
  kubectl diff -f mypod.yaml

  # The user should be able to use any diff tool
  KUBECTL_EXTERNAL_DIFF=fancydiff
  kdiff --ignore=.metadata.labels,.spec.affinity -- -f mydeploy.yaml
#+end_src


** Ideas

- Control over what is diffed
  - Limit the diff to a given =.kind= of resources, for example =Pod=
  - Limit the scope of the diff, for example to the resource =.spec=
  - Remove noisy fields from the diff, such as =last-applied-configuration=

- Ability to still choose custom diff tool
  - use any of =dyff=, =difftastic=, =delta= etc...

- Ability to use presets stored in $XDG_CONFIG/kdiff


** Design

- It should be possible to call the script interactively,
  or assign it directly to =KUBECTL_EXTERNAL_DIFF=
- If called interactively,
  the users original =KUBECTL_EXTERNAL_DIFF= should be taken into consideration


* Brainstorming instructions

- Help me brainstorm around this initial idea

- Help me produce and actionable plan, captured in Markdown format
- Structure your thoughts in three sections:
  - MVP design
    - Very actionable outline to code a minimal working version of the tool
  - Next steps
    - The most important improvements after MVP
  - Wild ideas
    - What inspires you!


* Agent context

The goal of this project is to enhance =argocd diff= and =kubectl diff=
by pre-processing manifests with arbitrary =yq= expression,
before applying the user's =KUBECTL_EXTERNAL_DIFF= program.

- The main script is =src/kdiff=
- You should regularly commit your changes to the current branch

** KUBECTL_EXTERNAL_DIFF calling conventions

The script  =src/kdiff-inspect= was shows the calling conventions used by =kubectl= and =argocd-diff=

=kubectl diff= calls =KUBECTL_EXTERNAL_DIFF= once,
with two directories containing all the files to compare.
#+begin_example
$ export KUBECTL_EXTERNAL_DIFF=kdiff-inspect
$ k diff -f v1_configmap_argocd-cm.yaml -f v1_configmap_argocd-cmd-params-cm.yaml
Argument list: /tmp/LIVE-3407625460 /tmp/MERGED-4175425960
Left: /tmp/LIVE-3407625460
v1.ConfigMap.argocd.argocd-cm
v1.ConfigMap.argocd.argocd-cmd-params-cm
Right: /tmp/MERGED-4175425960
v1.ConfigMap.argocd.argocd-cm
v1.ConfigMap.argocd.argocd-cmd-params-cm
#+end_example

=argocd diff= calls =KUBECTL_EXTERNAL_DIFF= once for each pair of files to compare.
#+begin_example
$ export KUBECTL_EXTERNAL_DIFF=kdiff-inspect
$ argocd app diff myapp
===== /ServiceAccount argocd/argocd-redis-ha-haproxy ======
Argument list: /tmp/argocd-diff3488706002/argocd-redis-ha-haproxy-live.yaml /tmp/argocd-diff3488706002/argocd-redis-ha-haproxy
Left: /tmp/argocd-diff3488706002/argocd-redis-ha-haproxy-live.yaml
/tmp/argocd-diff3488706002/argocd-redis-ha-haproxy-live.yaml
Right: /tmp/argocd-diff3488706002/argocd-redis-ha-haproxy
/tmp/argocd-diff3488706002/argocd-redis-ha-haproxy

===== /ServiceAccount argocd/argocd-repo-server ======
Argument list: /tmp/argocd-diff74211896/argocd-repo-server-live.yaml /tmp/argocd-diff74211896/argocd-repo-server
Left: /tmp/argocd-diff74211896/argocd-repo-server-live.yaml
/tmp/argocd-diff74211896/argocd-repo-server-live.yaml
Right: /tmp/argocd-diff74211896/argocd-repo-server
/tmp/argocd-diff74211896/argocd-repo-server
#+end_example
