#+TITLE: kdiff

=kdiff= lets you conveniently integrate YAML cleaning and comparison logic with =kubectl diff=.

Specify how your manifests should be filtered (i.e. "cleaned", or narrowed down in scope),
and how they shoud be compared, directly on the command line:
#+begin_src sh
  # Arguments after -- are passed to kubectl by default
  kdiff --transform 'yq .spec' --compare 'diff -u --color' -- -f mypod.yaml

  # A --yq shorthand is provided for convenience,
  # and KUBECTL_EXRTERNAL_DIFF is honored.
  # Thus, the following call is equivalent
  KUBECTL_EXTERNAL_DIFF='diff -u --color'
  kdiff --yq=.spec  -- -f mypod.yaml
#+end_src


A =--yq= shorthand can be used.
#+begin_src sh
  # Limit the diff to the configmap data
  kdiff --yq=.data  -- -f myconfig.yaml
#+end_src

If omitted, =--compare= defaults to =KUBECTL_EXTERNAL_DIFF=
#+begin_src sh
  KUBECTL_EXTERNAL_DIFF='dyff between -b'
  # Compare metadata, ignoring labels
  kdiff --yq='.metadata | del(.labels)' -- mypod.yaml
#+end_src

** Presets

Frequently used transform and compare combinations can be saved as *presets' in ="${KDIFF_CONFIG_DIR}"= (=${HOME}/.config/kdiff= by default).

Consider the following configuration layout:
#+begin_example
~/.config/kdiff
├── compare
│   ├── diff
│   └── dyff
└── transform
    └── clean
#+end_example

Use the executable =clean= in combination with the comparison program =dyff= by calling:
#+begin_src sh
  kdiff --preset clean:dyff -- -f mypod.yaml
#+end_src

Presets can be aliased:
#+begin_src sh
  echo "clean:dyff" >> "${KDIFF_CONFIG_DIR}/cleany"
  # Use 'cleany' or 'clean:diff' interchangeably
  kdiff --preset cleany -- -f mypod.yaml
#+end_src

Aliasing is mainly useful when using =kdiff= as =KUBECTL_EXTERNAL_DIFF=,
because arguments not matching =^[a-zA-Z0-9-=]+$= are [[https://github.com/kubernetes/kubectl/blob/8185d35b7a2cd69d364f0f09648ecdd94c9fb5b7/pkg/cmd/diff/diff.go#L197][stripped]] by =kubectl=.
An alias can be a simple alphanumeric string.

#+begin_src sh
  # Neither of the following would work:
  KUBECTL_EXTERNAL_DIFF='kdiff --yq=.data'
  KUBECTL_EXTERNAL_DIFF='kdiff --preset clean:dyff'
  # Use aliases instead
  KUBECTL_EXTERNAL_DIFF='kdiff --preset data-only'
  KUBECTL_EXTERNAL_DIFF='kdiff --preset cleany'
#+end_src

Happy diffing :)

** Installation

=kdiff= depends on [[https://github.com/mikefarah/yq][yq]] for YAML processing. If you haven't already, I encourage you to install it!

Clone the repository and use the =make install= command to install the =kdiff= script.
By default, this will install =kdiff= to =$HOME/.local/bin=, which should be in your PATH.

#+begin_src sh
  git clone https://your-repo-url/kdiff.git
  cd kdiff
  make install
#+end_src

You can customize the installation path using the =PREFIX= variable, for example for a system-wide installation (this may require sudo):
#+begin_src sh
  # Install to /usr/local/bin
  make install PREFIX=/usr/local
#+end_src

An =uninstall= target is also available to remove the script.

*** Presets

The included [[file:presets/][presets]] are optional and can be installed with a separate command:
#+begin_src sh
  make install-presets
#+end_src

This will copy the default presets to =$XDG_CONFIG_HOME/kdiff= (or =~/.config/kdiff=).

Note that some presets have external dependencies, such as [[https://github.com/itaysk/kubectl-neat][kubectl-neat]] and [[https://github.com/homeport/dyff][dyff]].
You will need to install them separately for the corresponding presets to work.

You can remove the presets with =make uninstall-presets=.
