* Problem statement

The goal of this project is to enhance =argocd diff= and =kubectl diff=
by allowing to process manifests with arbitrary yq expression,
before applying the user's =KUBECTL_EXTERNAL_DIFF= program.

** Advanced examples

#+begin_src bash
  # Assume the script is called kdiff
  # Should output a helpful message
  kdiff --help

  # Diff only the resource specs
  # Use kubectl diff as default command, and forward all arguments after --
  kdiff --scope=.spec -- -rR overlays/staging

  # Show the diff for services and pods
  kdiff --kind=svc,po -- argocd diff myapp

  # Use kdiff with a predefined set of arguments as KUBECTL_EXTERNAL_DIFF
  # kdiff should know wether it is invoked interactively, or as KUBECTL_EXTERNAL_DIFF
  export KUBECTL_EXTERNAL_DIFF="kdiff --yq '... style=\"\" | del(.metadata.labels)'"
  kubectl diff -f mypod.yaml

  # The user should be able to use any diff tool
  KUBECTL_EXTERNAL_DIFF=fancydiff
  kdiff --ignore=.metadata.labels,.spec.affinity -- -f mydeploy.yaml
#+end_src


** Ideas

- Control over what is diffed
  - Limit the diff to a given =.kind= of resources, for example =Pod=
  - Limit the scope of the diff, for example to the resource =.spec=
  - Remove noisy fields from the diff, such as =last-applied-configuration=

- Ability to still choose custom diff tool
  - use any of =dyff=, =difftastic=, =delta= etc...

- Ability to use presets stored in $XDG_CONFIG/kdiff


** Design

- It should be possible to call the script interactively,
  or assign it directly to =KUBECTL_EXTERNAL_DIFF=
- If called interactively,
  the users original =KUBECTL_EXTERNAL_DIFF= should be taken into consideration


* Brainstorming instructions

- Help me brainstorm around this initial idea

- Help me produce and actionable plan, captured in Markdown format
- Structure your thoughts in three sections:
  - MVP design
    - Very actionable outline to code a minimal working version of the tool
  - Next steps
    - The most important improvements after MVP
  - Wild ideas
    - What inspires you!


* Context

=kdiff= integrates arbitrary filtering and comparison logic with =kubectl diff=.

Specify how your manifests should be filtered (i.e. "cleaned", of narrowed down in scope),
and how they shoud be compared, directly on the command line:
#+begin_src sh
  # Arguments after -- are passed to kubectl by default
  kdiff --transform 'yq .spec' --compare 'diff -u --color' -- -f mypod.yaml

  # A --yq shorthand is provided for convenience,
  # and KUBECTL_EXRTERNAL_DIFF is honored.
  # Thus, the following call is equivalent
  KUBECTL_EXTERNAL_DIFF='diff -u --color'
  kdiff --yq=.spec  -- -f mypod.yaml
#+end_src


A =--yq= shorthand can be used.
#+begin_src sh
  # Limit the diff to the configmap data
  kdiff --yq=.data  -- -f myconfig.yaml
#+end_src

If omitted, =--compare= defaults to =KUBECTL_EXTERNAL_DIFF=
#+begin_src sh
  KUBECTL_EXTERNAL_DIFF='dyff between -b'
  # Compare metadata, ignoring labels
  kdiff --yq='.metadata | del(.labels)' -- mypod.yaml
#+end_src

** Presets

Frequently used transform and compare combinations can be saved as *presets' in ="${KDIFF_CONFIG_DIR}"= (=${HOME}/.config/kdiff= by default).

Consider the following configuration layout:
#+begin_example
~/.config/kdiff
├── compare
│   ├── diff
│   └── dyff
└── transform
    └── clean
#+end_example

Use the executable =clean= in combination with the comparison program =dyff= by calling:
#+begin_src sh
  kdiff --preset clean:dyff -- -f mypod.yaml
#+end_src

Presets can be aliased:
#+begin_src sh
  echo "clean:dyff" >> "${KDIFF_CONFIG_DIR}/cleany"
  # Use 'cleany' or 'clean:diff' interchangeably
  kdiff --preset cleany -- -f mypod.yaml
#+end_src

Aliasing is mainly useful when using =kdiff= as =KUBECTL_EXTERNAL_DIFF=,
because arguments not matching =^[a-zA-Z0-9-=]+$= are [[https://github.com/kubernetes/kubectl/blob/8185d35b7a2cd69d364f0f09648ecdd94c9fb5b7/pkg/cmd/diff/diff.go#L197][stripped]] by =kubectl=.
An alias can be a simple alphanumeric string.

#+begin_src sh
  # Neither of the following would work:
  KUBECTL_EXTERNAL_DIFF='kdiff --yq=.data'
  KUBECTL_EXTERNAL_DIFF='kdiff --preset clean:dyff'
  # Use aliases instead
  KUBECTL_EXTERNAL_DIFF='kdiff --preset data-only'
  KUBECTL_EXTERNAL_DIFF='kdiff --preset cleany'
#+end_src

Happy diffing :)
