# Default diff tool to use if KDIFF_TOOL is not set
diff_tool: "delta"

# Pre-defined filter sets
filters:
  # Common noise to ignore in any diff
  default_ignore:
    - .metadata.managedFields
    - .metadata.annotations["kubectl.kubernetes.io/last-applied-configuration"]
    - .status
  # A filter set for comparing just workload specs
  spec_only:
    - .spec

# Pre-defined command aliases or "profiles"
profiles:
  staging_check:
    command: "argocd diff staging-app --local manifests/staging"
    filters:
      - default_ignore
